AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB-Tabelle für MilesPictures

Resources:
  MilesPicturesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MilesPictures
      AttributeDefinitions:
        - AttributeName: pictureName
          AttributeType: S
      KeySchema:
        - AttributeName: pictureName
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: Production
